baseurl = "https://axoflow.com/docs/axosyslog-core/"
buildDrafts = false
googleAnalytics = "GTM-NPCJB3VK"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "GTM-NPCJB3VK"

[params]

url_latest_version = "https://axoflow.com/docs/axosyslog-core/"

# Content group for Google Analytics. Optional.
contentGroup = "axosyslog-docs"
